export interface ToolEntry {
  name: string;
  href: string;
  site: string;
  siteColor: string;
}

export const allTools: ToolEntry[] = [
  // Peregrine PDF (15)
  { name: "Merge PDF", href: "https://peregrinepdf.com/merge-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Split PDF", href: "https://peregrinepdf.com/split-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Compress PDF", href: "https://peregrinepdf.com/compress-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "PDF to JPG", href: "https://peregrinepdf.com/pdf-to-jpg", site: "PDF", siteColor: "#2563EB" },
  { name: "JPG to PDF", href: "https://peregrinepdf.com/jpg-to-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "PDF to PNG", href: "https://peregrinepdf.com/pdf-to-png", site: "PDF", siteColor: "#2563EB" },
  { name: "PNG to PDF", href: "https://peregrinepdf.com/png-to-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Rotate PDF", href: "https://peregrinepdf.com/rotate-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Watermark PDF", href: "https://peregrinepdf.com/watermark-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Unlock PDF", href: "https://peregrinepdf.com/unlock-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Protect PDF", href: "https://peregrinepdf.com/protect-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Sign PDF", href: "https://peregrinepdf.com/sign-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "Page Numbers", href: "https://peregrinepdf.com/add-page-numbers", site: "PDF", siteColor: "#2563EB" },
  { name: "OCR PDF", href: "https://peregrinepdf.com/ocr-pdf", site: "PDF", siteColor: "#2563EB" },
  { name: "PDF to Text", href: "https://peregrinepdf.com/pdf-to-text", site: "PDF", siteColor: "#2563EB" },

  // Peregrine Pix (16)
  { name: "Compress Image", href: "https://peregrinepix.com/compress-image", site: "Pix", siteColor: "#7C3AED" },
  { name: "Resize Image", href: "https://peregrinepix.com/resize-image", site: "Pix", siteColor: "#7C3AED" },
  { name: "Crop Image", href: "https://peregrinepix.com/crop-image", site: "Pix", siteColor: "#7C3AED" },
  { name: "Remove Background", href: "https://peregrinepix.com/remove-background", site: "Pix", siteColor: "#7C3AED" },
  { name: "PNG to JPG", href: "https://peregrinepix.com/png-to-jpg", site: "Pix", siteColor: "#7C3AED" },
  { name: "JPG to PNG", href: "https://peregrinepix.com/jpg-to-png", site: "Pix", siteColor: "#7C3AED" },
  { name: "WebP to JPG", href: "https://peregrinepix.com/webp-to-jpg", site: "Pix", siteColor: "#7C3AED" },
  { name: "WebP to PNG", href: "https://peregrinepix.com/webp-to-png", site: "Pix", siteColor: "#7C3AED" },
  { name: "JPG to WebP", href: "https://peregrinepix.com/jpg-to-webp", site: "Pix", siteColor: "#7C3AED" },
  { name: "PNG to WebP", href: "https://peregrinepix.com/png-to-webp", site: "Pix", siteColor: "#7C3AED" },
  { name: "SVG to PNG", href: "https://peregrinepix.com/svg-to-png", site: "Pix", siteColor: "#7C3AED" },
  { name: "Add Watermark", href: "https://peregrinepix.com/add-watermark", site: "Pix", siteColor: "#7C3AED" },
  { name: "Flip & Rotate", href: "https://peregrinepix.com/flip-rotate", site: "Pix", siteColor: "#7C3AED" },
  { name: "Favicon Generator", href: "https://peregrinepix.com/favicon-generator", site: "Pix", siteColor: "#7C3AED" },
  { name: "Image to Base64", href: "https://peregrinepix.com/image-to-base64", site: "Pix", siteColor: "#7C3AED" },
  { name: "Image Filters", href: "https://peregrinepix.com/image-filters", site: "Pix", siteColor: "#7C3AED" },

  // Peregrine Kit (31)
  { name: "Word Counter", href: "https://peregrinekit.com/word-counter", site: "Kit", siteColor: "#059669" },
  { name: "Character Counter", href: "https://peregrinekit.com/character-counter", site: "Kit", siteColor: "#059669" },
  { name: "Case Converter", href: "https://peregrinekit.com/case-converter", site: "Kit", siteColor: "#059669" },
  { name: "Lorem Ipsum Generator", href: "https://peregrinekit.com/lorem-ipsum-generator", site: "Kit", siteColor: "#059669" },
  { name: "Text Diff", href: "https://peregrinekit.com/text-diff", site: "Kit", siteColor: "#059669" },
  { name: "Remove Duplicates", href: "https://peregrinekit.com/remove-duplicates", site: "Kit", siteColor: "#059669" },
  { name: "Find & Replace", href: "https://peregrinekit.com/find-and-replace", site: "Kit", siteColor: "#059669" },
  { name: "Text to Slug", href: "https://peregrinekit.com/text-to-slug", site: "Kit", siteColor: "#059669" },
  { name: "Remove Line Breaks", href: "https://peregrinekit.com/remove-line-breaks", site: "Kit", siteColor: "#059669" },
  { name: "Markdown to HTML", href: "https://peregrinekit.com/markdown-to-html", site: "Kit", siteColor: "#059669" },
  { name: "HTML to Markdown", href: "https://peregrinekit.com/html-to-markdown", site: "Kit", siteColor: "#059669" },
  { name: "Readability Score", href: "https://peregrinekit.com/readability-score", site: "Kit", siteColor: "#059669" },
  { name: "Percentage Calculator", href: "https://peregrinekit.com/percentage-calculator", site: "Kit", siteColor: "#059669" },
  { name: "Age Calculator", href: "https://peregrinekit.com/age-calculator", site: "Kit", siteColor: "#059669" },
  { name: "Date Difference", href: "https://peregrinekit.com/date-difference", site: "Kit", siteColor: "#059669" },
  { name: "Unit Converter", href: "https://peregrinekit.com/unit-converter", site: "Kit", siteColor: "#059669" },
  { name: "Timezone Converter", href: "https://peregrinekit.com/timezone-converter", site: "Kit", siteColor: "#059669" },
  { name: "Tip Calculator", href: "https://peregrinekit.com/tip-calculator", site: "Kit", siteColor: "#059669" },
  { name: "BMI Calculator", href: "https://peregrinekit.com/bmi-calculator", site: "Kit", siteColor: "#059669" },
  { name: "Mortgage Calculator", href: "https://peregrinekit.com/mortgage-calculator", site: "Kit", siteColor: "#059669" },
  { name: "Compound Interest", href: "https://peregrinekit.com/compound-interest", site: "Kit", siteColor: "#059669" },
  { name: "Salary Calculator", href: "https://peregrinekit.com/salary-calculator", site: "Kit", siteColor: "#059669" },
  { name: "GPA Calculator", href: "https://peregrinekit.com/gpa-calculator", site: "Kit", siteColor: "#059669" },
  { name: "Meta Tag Generator", href: "https://peregrinekit.com/meta-tag-generator", site: "Kit", siteColor: "#059669" },
  { name: "Open Graph Preview", href: "https://peregrinekit.com/open-graph-preview", site: "Kit", siteColor: "#059669" },
  { name: "Robots.txt Generator", href: "https://peregrinekit.com/robots-txt-generator", site: "Kit", siteColor: "#059669" },
  { name: "Sitemap Generator", href: "https://peregrinekit.com/sitemap-generator", site: "Kit", siteColor: "#059669" },
  { name: "UTM Builder", href: "https://peregrinekit.com/utm-builder", site: "Kit", siteColor: "#059669" },
  { name: "QR Code Generator", href: "https://peregrinekit.com/qr-code-generator", site: "Kit", siteColor: "#059669" },
  { name: "Heading Checker", href: "https://peregrinekit.com/heading-checker", site: "Kit", siteColor: "#059669" },
  { name: "Text to Speech", href: "https://peregrinekit.com/text-to-speech", site: "Kit", siteColor: "#059669" },

  // Peregrine Vid (13)
  { name: "Video to MP4", href: "https://peregrinevid.com/convert-to-mp4", site: "Vid", siteColor: "#E11D48" },
  { name: "Video to MP3", href: "https://peregrinevid.com/video-to-mp3", site: "Vid", siteColor: "#E11D48" },
  { name: "Video to GIF", href: "https://peregrinevid.com/video-to-gif", site: "Vid", siteColor: "#E11D48" },
  { name: "Compress Video", href: "https://peregrinevid.com/compress-video", site: "Vid", siteColor: "#E11D48" },
  { name: "Trim Video", href: "https://peregrinevid.com/trim-video", site: "Vid", siteColor: "#E11D48" },
  { name: "Audio to MP3", href: "https://peregrinevid.com/convert-to-mp3", site: "Vid", siteColor: "#E11D48" },
  { name: "WAV to MP3", href: "https://peregrinevid.com/wav-to-mp3", site: "Vid", siteColor: "#E11D48" },
  { name: "MP3 to WAV", href: "https://peregrinevid.com/mp3-to-wav", site: "Vid", siteColor: "#E11D48" },
  { name: "Extract Audio", href: "https://peregrinevid.com/extract-audio", site: "Vid", siteColor: "#E11D48" },
  { name: "Compress Audio", href: "https://peregrinevid.com/compress-audio", site: "Vid", siteColor: "#E11D48" },
  { name: "Video to WebM", href: "https://peregrinevid.com/video-to-webm", site: "Vid", siteColor: "#E11D48" },
  { name: "Screen Recorder", href: "https://peregrinevid.com/screen-recorder", site: "Vid", siteColor: "#E11D48" },
  { name: "Trim Audio", href: "https://peregrinevid.com/trim-audio", site: "Vid", siteColor: "#E11D48" },

  // Peregrine Dev (26)
  { name: "JSON Formatter", href: "https://peregrinedev.com/json-formatter", site: "Dev", siteColor: "#D97706" },
  { name: "JSON Validator", href: "https://peregrinedev.com/json-validator", site: "Dev", siteColor: "#D97706" },
  { name: "JSON to CSV", href: "https://peregrinedev.com/json-to-csv", site: "Dev", siteColor: "#D97706" },
  { name: "CSV to JSON", href: "https://peregrinedev.com/csv-to-json", site: "Dev", siteColor: "#D97706" },
  { name: "Regex Tester", href: "https://peregrinedev.com/regex-tester", site: "Dev", siteColor: "#D97706" },
  { name: "Base64 Encode/Decode", href: "https://peregrinedev.com/base64", site: "Dev", siteColor: "#D97706" },
  { name: "URL Encode/Decode", href: "https://peregrinedev.com/url-encode", site: "Dev", siteColor: "#D97706" },
  { name: "Hash Generator", href: "https://peregrinedev.com/hash-generator", site: "Dev", siteColor: "#D97706" },
  { name: "UUID Generator", href: "https://peregrinedev.com/uuid-generator", site: "Dev", siteColor: "#D97706" },
  { name: "Color Picker", href: "https://peregrinedev.com/color-picker", site: "Dev", siteColor: "#D97706" },
  { name: "Hex to RGB", href: "https://peregrinedev.com/hex-to-rgb", site: "Dev", siteColor: "#D97706" },
  { name: "Cron Builder", href: "https://peregrinedev.com/cron-builder", site: "Dev", siteColor: "#D97706" },
  { name: "JWT Decoder", href: "https://peregrinedev.com/jwt-decoder", site: "Dev", siteColor: "#D97706" },
  { name: "HTML Minifier", href: "https://peregrinedev.com/html-minifier", site: "Dev", siteColor: "#D97706" },
  { name: "CSS Minifier", href: "https://peregrinedev.com/css-minifier", site: "Dev", siteColor: "#D97706" },
  { name: "JS Minifier", href: "https://peregrinedev.com/js-minifier", site: "Dev", siteColor: "#D97706" },
  { name: "SQL Formatter", href: "https://peregrinedev.com/sql-formatter", site: "Dev", siteColor: "#D97706" },
  { name: "Diff Checker", href: "https://peregrinedev.com/diff-checker", site: "Dev", siteColor: "#D97706" },
  { name: "Timestamp Converter", href: "https://peregrinedev.com/timestamp-converter", site: "Dev", siteColor: "#D97706" },
  { name: "Password Generator", href: "https://peregrinedev.com/password-generator", site: "Dev", siteColor: "#D97706" },
  { name: "Markdown Preview", href: "https://peregrinedev.com/markdown-preview", site: "Dev", siteColor: "#D97706" },
  { name: "Color Palette Generator", href: "https://peregrinedev.com/color-palette", site: "Dev", siteColor: "#D97706" },
  { name: "YAML Formatter", href: "https://peregrinedev.com/yaml-formatter", site: "Dev", siteColor: "#D97706" },
  { name: "JSON to YAML", href: "https://peregrinedev.com/json-to-yaml", site: "Dev", siteColor: "#D97706" },
  { name: "YAML to JSON", href: "https://peregrinedev.com/yaml-to-json", site: "Dev", siteColor: "#D97706" },
  { name: "Color Contrast Checker", href: "https://peregrinedev.com/contrast-checker", site: "Dev", siteColor: "#D97706" },
];

/** Site order for grouping results */
export const siteOrder = ["PDF", "Pix", "Vid", "Dev", "Kit"] as const;
